{
 "title": "Twitter Sentiment Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tweets Distribution per Country",
   "type": "grafana-worldmap-panel",
   "description": "Count of tweets per received location",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "place_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "languages",
     "query": "SELECT mean(\"latitude\") AS \"latitude\", mean(\"longitude\") AS \"longitude\", count(\"id\") AS \"count\" FROM \"languages\" WHERE (\"country_code\" <> '') AND $timeFilter GROUP BY \"country_code\" fill(0)",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "place_name", "operator": "=", "value": "US" }
     ]
    }
   ]
  },
  {
   "title": "World Tweets Distribution",
   "type": "grafana-worldmap-panel",
   "description": "Count of tweets per received location",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "place_name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "languages",
     "query": "SELECT mean(\"latitude\") AS \"latitude\", mean(\"longitude\") AS \"longitude\", count(\"id\") AS \"count\" FROM \"languages\" WHERE (\"place_name\" <> '') AND $timeFilter GROUP BY \"place_name\" fill(0)",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "place_name", "operator": "=", "value": "US" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Total number of tweets processed during the selected time-frame.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Total count of positive tweets processed during the selected time-frame.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "polarity", "operator": "=", "value": "Positive" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Total count of negative tweets processed during the selected time-frame.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "polarity", "operator": "=", "value": "Negative" }
     ]
    }
   ]
  },
  {
   "title": "Polarity Counts",
   "type": "graph",
   "description": "Representation of the number of tweets classified by polarity for a given point it time. Top graph is for positive tweets, and bottom graph is for negatives.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positive counts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "polarity", "operator": "=", "value": "Positive" }
     ]
    },
    {
     "alias": "Negative counts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "polarity", "operator": "=", "value": "Negative" }
     ]
    }
   ]
  },
  {
   "title": "World Positivity Index :-)",
   "type": "gauge",
   "description": "Ratio between number of positive tweets vs. negative tweets.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "query": "SELECT \"count_p\" / \"count_n\" FROM (SELECT count(\"id\") AS \"count_p\" FROM \"sentiments\" WHERE \"polarity\" = 'Positive' AND $timeFilter), (SELECT count(\"id\") AS \"count_n\" FROM \"sentiments\" WHERE \"polarity\" = 'Negative' AND $timeFilter) fill(previous)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Languages Distribution",
   "type": "grafana-piechart-panel",
   "description": "Count of tweets received for each language.",
   "gridPos": { "h": 6, "w": 12, "x": 7, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_language",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "language" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "languages",
     "query": "SELECT count(\"id\") FROM \"autogen\".\"languages\" WHERE (\"language\" <> 'und') AND $timeFilter GROUP BY time($__interval), \"language\" fill(none)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "language", "operator": "<>", "value": "und" }
     ]
    }
   ]
  },
  {
   "title": "Polarity Distribution",
   "type": "grafana-piechart-panel",
   "description": "Proportion of positive tweets vs. negative tweets",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Positive tweets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "polarity", "operator": "=", "value": "Positive" }
     ]
    },
    {
     "alias": "Negative tweets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sentiments",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "polarity", "operator": "=", "value": "Negative" }
     ]
    }
   ]
  }
 ]
}